Integration of the new dashboard loading animation
armada-ths/ais pull request #1039
Opened 2023-09-06 15:57 UTC by ferran98campos

The commit replaces the 'Loading...' word for an animation of the armada ship sailing the sea. This animation will only appear while the users' dashboard is being loaded.

## Describe your changes
- Added a new image with the armada ship in #00d790 green
- Create the ship and wave animations
- The 'loading...' is replaced by that animation

Fixes: #1005

## Checklist before requesting review

- [ ] Feature/fix PRs should add one atomic (as small as possible) feature or fix.
- [ ] The code compiles and all the tests pass.

2023-09-06 16:00 UTC, ferran98campos commented
Since the dashboard loading is relatively fast, here's an example of how the animation looks. 

[https://drive.google.com/file/d/1_ILMQ2aRRxxzH8WyipEkxJ6-w37CxBLz/view?usp=sharing](url)

2023-09-11 21:21 UTC, didrikmunther commented on apps/complete_registration/src/main.tsx
> +                <p className="font-medium pt-5">Loading...</p>
Could we extract this to a atomic component?

2023-09-11 21:22 UTC, didrikmunther requested changes
Looks great!

1. I left a comment
2. You need to run `pnpm build` and commit the build files because we haven't setup automatic building of this project yet unfortunately.

2023-09-11 21:22 UTC, didrikmunther commented on apps/complete_registration/src/main.tsx
> +                <p className="font-medium pt-5">Loading...</p>
Could we extract this to a atomic component?

2023-09-28 15:47 UTC, didrikmunther approved these changes
LGTM, very nice!

2023-09-28 16:15 UTC, Hampfh approved these changes
Nice work!

2023-09-28 16:17 UTC, merged