Lucia/feature/add 'all' line in ais statistics
armada-ths/ais pull request #1227
Opened 2024-05-29 17:33 UTC by luciakar

Added a line with all signatures in the graph in fairs/2024/companies/statistics:
![bild](https://github.com/armada-ths/ais/assets/167246860/cd89db78-3d60-41bc-9796-de409675f80e)

2024-06-12 13:16 UTC, didrikmunther requested changes
Looks great!

The `companies/view.py` is not formatted correctly. Once that is fixed we can merge it!

https://github.com/armada-ths/ais/actions/runs/9290592635/job/25567159580?pr=1227

2024-06-17 10:09 UTC, didrikmunther requested changes

2024-06-17 10:09 UTC, didrikmunther commented on companies/views.py
> +        print(table)
Remove print please!

2024-06-17 10:37 UTC, luciakar commented on companies/views.py
> +        print(table)
done!

2024-06-18 20:20 UTC, merged