feat: Implement new Final Registration (FR) Page
armada-ths/ais pull request #883
Opened 2023-07-11 17:03 UTC by ferran98campos

## Describe your changes

The user registration page 'https://register.armada.nu/register/user' style has been changed in order to make it more accessible since people noticed the previous version confused some clients.

Fixes: #

- The form is now a stepped form that allows users to keep track of the different steps the form has, and in which one they are currently in.
- For them to select a company, a company browser has been developed to replace the old dropdown menu which contained 1000+ companies. Now, some companies will show up (10 companies MAX) that match what they wrote in the browser. For that, a new API endpoint has been created.

## Checklist before requesting review

- [ ] Feature/fix PRs should add one atomic (as small as possible) feature or fix.
- [ ] The code compiles and all the tests pass.

2023-07-11 17:04 UTC, ferran98campos commented
How it used to look like: 
![image](https://github.com/armada-ths/ais/assets/73848801/afb863ec-4689-4851-bcb0-efd9925c58f6)

New version: 
![image](https://github.com/armada-ths/ais/assets/73848801/2c0879ed-e292-4add-8963-e11daf370153)

2023-07-16 18:35 UTC, didrikmunther requested changes
I've left some nitpicks and general questions. A part of the README as well as an onboarding script is also missing, but overall I find this to be a very nice solution and I really love the commented code in the JS script. The new page looks fantastic!

2023-07-16 18:35 UTC, didrikmunther commented on api/views.py
> +def status(request):
I remember deleting this function/endpoint, it must have gotten readded in this PR. Could you delete it?

2023-07-16 18:35 UTC, didrikmunther commented on docs/README.md
> -## Creating Database Migrations
Why is this part of the README being deleted?

2023-07-16 18:35 UTC, didrikmunther commented on make-migration.sh
Why is this file being deleted?

2023-07-16 18:35 UTC, didrikmunther commented on templates/register/outside/create_user.html
> +    <!--
Why is this block commented out? Is there another place where you can create a new company? Can we remove the commented out code?

2023-07-16 18:35 UTC, didrikmunther commented on templates/register/outside/create_user.html
> +						{% csrf_token %} {{ contact_form | crispy }}
Why is this block commented out? Can we remove it?

2023-07-17 14:43 UTC, didrikmunther commented on api/views.py
> +def status(request):
No, I was referring to the `status` function on line 371.

2023-07-17 17:11 UTC, didrikmunther approved these changes
Very nice job!

2023-07-18 15:40 UTC, merged